// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdTtzPf2EUAxQjI3Bg0EFw0rIfHd2AJw4',
    appId: '1:964457949557:web:9aaba99b0f7724f829cb3c',
    messagingSenderId: '964457949557',
    projectId: 'cammo-pager',
    authDomain: 'cammo-pager.firebaseapp.com',
    storageBucket: 'cammo-pager.firebasestorage.app',
    measurementId: 'G-LEVVNKTVFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_TXwsp6M6EXllSJ2hBz0f5zl4lbsCldc',
    appId: '1:964457949557:android:acfb1c6909f88bef29cb3c',
    messagingSenderId: '964457949557',
    projectId: 'cammo-pager',
    storageBucket: 'cammo-pager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-0KMQk4zrC59SfKSrycbh3mmsoLd8ec',
    appId: '1:964457949557:ios:4e3902adc51f003529cb3c',
    messagingSenderId: '964457949557',
    projectId: 'cammo-pager',
    storageBucket: 'cammo-pager.firebasestorage.app',
    iosClientId: '964457949557-kvf8jr3kb7btl8ckgfmkgt001prhrsit.apps.googleusercontent.com',
    iosBundleId: 'com.squadqwat.mobilePagerFlutter',
  );
}